push = false
publish = false
release = false
allow-branch = ["master"]
shared-version = "workspace"
tag = false
consolidate-commits = false
pre-release-commit-message = "chore(release): v{{version}}"
