include = ["**/Cargo.toml", ".cargo/audit.toml", "rustfmt.toml", "taplo.toml"]

[schema]
path = "https://taplo.tamasfe.dev/schemas/Cargo.toml.json"

[formatting]
allowed_blank_lines = 1
array_auto_collapse = true
array_auto_expand = true
compact_arrays = true
indent_string = "    "
trailing_newline = true

[[rule]]
formatting = { reorder_arrays = true, reorder_keys = true }
include = ["Cargo.toml"]
keys = ["workspace", "workspace.dependencies", "workspace.dev-dependencies"]

[[rule]]
formatting = { reorder_arrays = true, reorder_keys = true }
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies"]

[[rule]]
formatting = { reorder_arrays = true, reorder_keys = true }
include = ["rustfmt.toml"]
