[package]
name = "bpx-api-client"
authors = ["Backpack <security@backpack.exchange>"]
license = "Apache-2.0"
version = "0.2.4"
edition = "2021"
description = "Rust client for Backpack Exchange"
repository = "https://github.com/backpack-exchange/bpx-api-client/tree/master/rust/client"

[dependencies]
base64 = { workspace = true }
bpx-api-types = { version = "0.1.4", path = "../types" }
ed25519-dalek = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
