[package]
name = "bpx-api-client"
authors = ["Backpack <security@backpack.exchange>"]
license = "Apache-2.0"
version = "0.1.3"
edition = "2021"
description = "Rust client for Backpack Exchange"

[dependencies]
base64 = { workspace = true }
bpx-api-types = { version = "0.1.1", path = "../types" }
ed25519-dalek = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
