[workspace]
members = ["client", "types"]
resolver = "2"

[workspace.dependencies]
base64 = "0.21.5"
chrono = { version = "0.4.31", features = ["serde"] }
ed25519-dalek = "2.1.0"
reqwest = { version = "0.11.22", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rust_decimal = "1.33.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
tracing = "0.1.40"
