[package]
name = "bpx-api-types"
authors = ["Backpack <security@backpack.exchange>"]
license = "Apache-2.0"
version = "0.1.1"
edition = "2021"
description = "Backpack Exchange types"

[dependencies]
chrono = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
