[package]
name = "bpx-api-types"
authors = ["Backpack <security@backpack.exchange>"]
license = "Apache-2.0"
version = "0.1.4"
edition = "2021"
description = "Backpack Exchange types"
repository = "https://github.com/backpack-exchange/bpx-api-client/rust/types"

[dependencies]
chrono = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
